pub mod linear_search;
pub mod smallest_in_array;
pub mod reverse_array;
pub mod single_number;
pub mod maximum_subarray;
pub mod pair_sum;
pub mod majority_element;
pub mod buy_sell_stock;
pub mod container_with_most_water;